const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const root=path.join(__dirname,'..');const admin=fs.readFileSync(path.join(root,'routes/admin.js'),'utf8');const auth=fs.readFileSync(path.join(root,'middleware/auth.js'),'utf8');const server=fs.readFileSync(path.join(root,'server.js'),'utf8');const ui=fs.readFileSync(path.join(root,'admin-ui/index.html'),'utf8');const js=fs.readFileSync(path.join(root,'admin-ui/admin.js'),'utf8');
test('all requested admin page routes are server-gated',()=>{for(const p of ['/admin/login','/admin/dashboard','/admin/users','/admin/users/:id','/admin/wallets','/admin/deposits','/admin/transactions','/admin/networks','/admin/tokens','/admin/copy-trading','/admin/notifications','/admin/reports','/admin/audit-logs','/admin/settings'])assert.match(server,new RegExp(p.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')))});
test('role matrix matches requested authority boundaries',()=>{assert.match(auth,/ADMIN_ROLES=\['super_admin','admin','support','finance','auditor','content_manager'\]/);assert.match(auth,/admin:\['users:read','users:write','transactions:read','transactions:write','support:read','support:write'\]/);assert.match(auth,/support:\['users:read','support:read','support:write'\]/);assert.match(auth,/finance:\['users:read','transactions:read','deposits:read','deposits:write','withdrawals:read','withdrawals:write','reports:read','networks:read','tokens:read'\]/);assert.match(auth,/auditor:\['users:read'.*'audit:read'\]/s);assert.match(auth,/content_manager:\['notifications:read','notifications:write','content:read','content:write'\]/)});
test('role changes are Super Admin only',()=>assert.ok(admin.includes("if(req.body.role!==undefined){if(req.user.role!=='super_admin')return res.status(403)")));
test('admin IP allow-list is enforced on every protected admin API request',()=>assert.match(admin,/Enforce the admin IP allow-list/));
test('sensitive financial actions require explicit confirmation',()=>assert.match(admin,/deposits.*approve.*reject.*withdrawals.*approve.*send.*complete.*reject.*reverse/s));
test('requested admin UI sections and support controls exist',()=>{for(const s of ['dashboard','users','deposits','transactions','networks','tokens','copy-trading','notifications','reports','audit','settings','support'])assert.ok(ui.includes(`data-section="${s}"`));assert.match(js,/loadSupport/);assert.match(ui,/exportPdf/) });
test('no existing project files were removed',()=>{const archive=process.env.ORIGINAL_PROJECT_ARCHIVE;const manifestPath=path.join(root,'tests','original-files-manifest.json');let before=[];if(archive&&fs.existsSync(archive)){const {execFileSync}=require('node:child_process');before=execFileSync('unzip',['-Z1',archive],{encoding:'utf8'}).split(/\r?\n/).filter(Boolean)}else if(fs.existsSync(manifestPath)){before=JSON.parse(fs.readFileSync(manifestPath,'utf8')).files}else{return}for(const f of before)assert.ok(fs.existsSync(path.join(root,f.replace(/^[^/]+\//,'')))||fs.existsSync(path.join(root,f)),`Missing original path: ${f}`)});
