const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const root=path.join(__dirname,'..');const read=p=>fs.readFileSync(path.join(root,p),'utf8');
test('real blockchain verifier uses chain RPC/TronGrid and never normalized mock response',()=>{const s=read('services/blockchainVerificationService.js');assert.match(s,/eth_getTransactionReceipt/);assert.match(s,/ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef/);assert.match(s,/walletsolidity\/gettransactioninfobyid/);assert.doesNotMatch(s,/data\.verified!==true/)});
test('admin 2FA fields and routes are present',()=>{const u=read('models/User.js'),a=read('routes/admin.js');assert.match(u,/twoFactorSecret/);assert.match(a,/2fa\/setup\/start/);assert.match(a,/2fa\/setup\/verify/);assert.match(a,/REQUIRE_ADMIN_2FA==='true'/)});
test('registration referral remains optional and admin 2FA is mandatory',()=>{const a=read('routes/auth.js'),r=read('routes/admin.js'),s=read('server.js');assert.match(a,/Name, email and password are required/);assert.match(a,/normalizedInvite/);assert.match(a,/if\(!code\)return res\.status\(401\)/);assert.match(a,/if\(!verifyTotp/);assert.match(r,/REQUIRE_ADMIN_2FA==='true'/);assert.doesNotMatch(s,/const blocked=\/sqlmap\|nikto/);});
test('KYC gate protects withdrawals and investments',()=>{assert.match(read('services/withdrawalService.js'),/REQUIRE_KYC_FOR_WITHDRAWALS/);assert.match(read('services/investmentService.js'),/REQUIRE_KYC_FOR_INVESTMENTS/)});
test('old UI files remain and new visual UI is present',()=>{for(const f of ['public/index.html','public/login.html','public/register.html','public/dashboard.html','public/deposit.html','public/withdraw.html','public/market.html','public/profile.html','public/referrals.html'])assert.ok(fs.existsSync(path.join(root,f)));assert.ok(fs.existsSync(path.join(root,'public/app-ui-v2.css')));assert.ok(fs.existsSync(path.join(root,'admin-ui/index.html')))});

test('investment ROI is stored at plan selection and settled into the ledger',()=>{assert.match(read('models/InvestmentPlan.js'),/roiPercent/);assert.match(read('models/Investment.js'),/roiPercent/);assert.match(read('services/investmentSettlementService.js'),/percentOf/)});

test('admin control surface has dedicated routes and role guards',()=>{const a=read('routes/admin.js'),srv=read('server.js'),html=read('admin-ui/index.html');for(const x of ['/users/:id','/networks','/tokens','/copy-trading','/notifications','/content/:key','/reports/summary','/reports/transactions.csv'])assert.match(a,new RegExp(x.replace(/[/:]/g,'\\$&')));assert.match(a,/requirePermission/);for(const x of ['/admin/login','/admin/dashboard','/admin/networks','/admin/tokens','/admin/copy-trading','/admin/reports'])assert.ok(srv.includes(x));for(const x of ['networks','tokens','copy-trading','notifications','reports'])assert.ok(html.includes('data-section=\"'+x+'\"'));});
