const router=require('express').Router();const bcrypt=require('bcrypt');const jwt=require('jsonwebtoken');const crypto=require('crypto');const rateLimit=require('express-rate-limit');const User=require('../models/User');const Referral=require('../models/Referral');
const {getSetting}=require('../services/platformSettingsService');
const {verifyTotp}=require('../services/totp');
const cookieOptions=()=>({httpOnly:true,sameSite:'lax',secure:String(process.env.NODE_ENV).toLowerCase()==='production',path:'/',maxAge:1000*60*60*24*7});
const limiter=rateLimit({windowMs:15*60*1000,max:20,standardHeaders:true,legacyHeaders:false,skipSuccessfulRequests:true,keyGenerator:(req)=>`${req.ip}:${String(req.body?.email||'').trim().toLowerCase()||'unknown'}`,handler:(req,res)=>res.status(429).json({success:false,message:'محاولات تسجيل الدخول كثيرة. انتظر قليلًا ثم حاول مجددًا.'})});
async function token(user){let expires=process.env.JWT_EXPIRES_IN||'7d';if(['super_admin','admin','support','finance','auditor','content_manager'].includes(user.role)){const sec=await getSetting('adminSecurity');expires=`${Math.min(1440,Math.max(5,Number(sec?.sessionMinutes||60)))}m`;}return jwt.sign({sub:user._id.toString(),role:user.role,sv:user.sessionVersion||0},process.env.JWT_SECRET,{algorithm:'HS256',expiresIn:expires,issuer:'crypinvest',audience:'crypinvest-users'});}
async function code(){for(let i=0;i<20;i++){const c=crypto.randomBytes(5).toString('hex').toUpperCase();if(!(await User.exists({referralCode:c})))return c;}throw new Error('Could not generate referral code.');}
router.post('/register',limiter,async(req,res)=>{try{const {name,email,password,inviteCode}=req.body||{};if(!name||!email||!password)return res.status(400).json({success:false,message:'Name, email and password are required.'});if(password.length<8)return res.status(400).json({success:false,message:'Password must be at least 8 characters.'});const normalizedInvite=String(inviteCode||'').trim().toUpperCase();const sponsor=normalizedInvite?await User.findOne({referralCode:normalizedInvite,status:{$in:['active','pending']}}):null;if(normalizedInvite&&!sponsor)return res.status(400).json({success:false,message:'Invalid invite code.'});if(await User.exists({email:String(email).toLowerCase()}))return res.status(409).json({success:false,message:'Email is already registered.'});const session=await User.startSession();let u;try{await session.withTransaction(async()=>{const hash=await bcrypt.hash(password,Number(process.env.BCRYPT_ROUNDS||12));u=(await User.create([{name,email:String(email).toLowerCase(),passwordHash:hash,referralCode:await code(),sponsor:sponsor?._id||null,status:'active'}],{session}))[0];const ancestors=[];let cursor=sponsor;for(let level=1;level<=3&&cursor;level++){ancestors.push({sponsor:cursor._id,referredUser:u._id,referralCode:cursor.referralCode,level,status:'active',activatedAt:new Date()});cursor=cursor.sponsor?await User.findById(cursor.sponsor).session(session):null;}await Referral.create(ancestors,{session});if(sponsor){await User.updateOne({_id:sponsor._id},{$inc:{directReferralsCount:1,totalReferralsCount:1}},{session});}if(ancestors.length>1){const increments=ancestors.slice(1).map(a=>User.updateOne({_id:a.sponsor},{$inc:{totalReferralsCount:1}},{session}));await Promise.all(increments);}});}finally{await session.endSession();}const t=await token(u);res.cookie?res.cookie('ci_session',t,cookieOptions()):res.setHeader('Set-Cookie',`ci_session=${encodeURIComponent(t)}; Path=/; Max-Age=${60*60*24*7}; HttpOnly; SameSite=Lax${String(process.env.NODE_ENV).toLowerCase()==='production'?'; Secure':''}`);res.status(201).json({success:true,user:u.toSafeObject()});}catch(e){res.status(500).json({success:false,message:e.message});}});
router.post('/logout',async(req,res)=>{res.setHeader('Set-Cookie','ci_session=; Path=/; Max-Age=0; HttpOnly; SameSite=Lax'+(String(process.env.NODE_ENV).toLowerCase()==='production'?'; Secure':''));res.json({success:true});});
router.post('/login',limiter,async(req,res)=>{try{const {email,password}=req.body||{};const u=await User.findOne({email:String(email||'').toLowerCase()}).select('+passwordHash');if(!u||u.status==='blocked'||u.status==='suspended')return res.status(401).json({success:false,message:'Invalid credentials.'});if(u.isLocked)return res.status(423).json({success:false,message:'الحساب مقفل مؤقتًا بسبب محاولات فاشلة. حاول لاحقًا.'});const ok=await bcrypt.compare(String(password||''),u.passwordHash);if(!ok){u.failedLoginAttempts=Number(u.failedLoginAttempts||0)+1;if(u.failedLoginAttempts>=10){u.lockedUntil=new Date(Date.now()+2*60*1000);u.failedLoginAttempts=0;}await u.save();return res.status(401).json({success:false,message:'البريد الإلكتروني أو كلمة المرور غير صحيحة.'});}if(['super_admin','admin','support','finance','auditor','content_manager'].includes(u.role)){
const adminSecurity=await getSetting('adminSecurity');const allowedIPs=Array.isArray(adminSecurity?.allowedIPs)?adminSecurity.allowedIPs:[];if(allowedIPs.length&&!allowedIPs.includes(String(req.ip)))return res.status(403).json({success:false,message:'عنوان IP غير مسموح لحساب الإدارة.',code:'ADMIN_IP_DENIED'});
if(!u.twoFactorEnabled)return res.status(403).json({success:false,message:'يجب تفعيل 2FA لحسابات الإدارة قبل تسجيل الدخول.',code:'ADMIN_2FA_REQUIRED'});
const code=String(req.body.twoFactorCode||req.body.otp||'').trim();if(!code)return res.status(401).json({success:false,message:'أدخل رمز التحقق بخطوتين للمتابعة.',requiresTwoFactor:true});if(!verifyTotp(u.twoFactorSecret,code,1))return res.status(401).json({success:false,message:'رمز التحقق بخطوتين غير صحيح.',requiresTwoFactor:true});}u.failedLoginAttempts=0;u.lockedUntil=null;u.lastLoginAt=new Date();u.lastLoginIp=String(req.ip||'').slice(0,100);u.lastLoginUserAgent=String(req.get('user-agent')||'').slice(0,500);u.loginHistory=[...(u.loginHistory||[]).slice(-19),{at:new Date(),ip:String(req.ip||'').slice(0,100),userAgent:String(req.get('user-agent')||'').slice(0,500)}];await u.save();const t=await token(u);res.setHeader('Set-Cookie',`ci_session=${encodeURIComponent(t)}; Path=/; Max-Age=${60*60*24*7}; HttpOnly; SameSite=Lax${String(process.env.NODE_ENV).toLowerCase()==='production'?'; Secure':''}`);res.json({success:true,user:u.toSafeObject(),requiresTwoFactor:false});}catch(e){res.status(500).json({success:false,message:e.message});}});
module.exports=router;
