const router=require('express').Router();const KycProfile=require('../models/KycProfile');const bcrypt=require('bcrypt');const {requireAuth,requireActiveAccount}=require('../middleware/auth');const User=require('../models/User');const Referral=require('../models/Referral');const Transaction=require('../models/Transaction');
router.use(requireAuth);
router.get('/me',(req,res)=>res.json({success:true,user:req.user.toSafeObject()}));
router.get('/referral-code',(req,res)=>res.json({success:true,referralCode:req.user.referralCode}));
router.get('/referrals',async(req,res,next)=>{try{const items=await Referral.find({sponsor:req.user._id,level:1}).populate('referredUser','name email referralCode status createdAt').sort({createdAt:-1});res.json({success:true,items});}catch(e){next(e);}});
router.get('/referrals/tree',async(req,res,next)=>{try{const levels=Math.min(10,Math.max(1,Number(req.query.levels||5)));let nodes=0;const MAX_NODES=2000;async function build(parentId,level){if(level>levels||nodes>=MAX_NODES)return[];const remaining=MAX_NODES-nodes;const users=await User.find({sponsor:parentId}).select('name email referralCode status createdAt sponsor').sort({createdAt:1}).limit(remaining).lean();nodes+=users.length;return Promise.all(users.map(async u=>({...u,level,parentId:String(parentId),children:await build(u._id,level+1)})));}const tree=await build(req.user._id,1);res.json({success:true,levels,nodes,limited:nodes>=MAX_NODES,tree});}catch(e){next(e);}});
router.get('/referrals/stats',async(req,res,next)=>{try{const [direct,total]=await Promise.all([Referral.countDocuments({sponsor:req.user._id,level:1}),Referral.countDocuments({sponsor:req.user._id})]);const active=await Referral.countDocuments({sponsor:req.user._id,status:'active'});res.json({success:true,stats:{direct,active,total}});}catch(e){next(e);}});
router.get('/transactions',requireActiveAccount,async(req,res,next)=>{try{const limit=Math.min(100,Math.max(1,Number(req.query.limit||30)));const page=Math.max(1,Number(req.query.page||1));const q={user:req.user._id};if(req.query.type)q.type=req.query.type;const [items,total]=await Promise.all([Transaction.find(q).sort({createdAt:-1}).skip((page-1)*limit).limit(limit),Transaction.countDocuments(q)]);res.json({success:true,items,total,page,limit,pages:Math.ceil(total/limit)});}catch(e){next(e);}});
router.patch('/profile',requireActiveAccount,async(req,res,next)=>{try{const name=String(req.body.name||'').trim();if(name.length<2||name.length>100)return res.status(400).json({success:false,message:'Name must be 2-100 characters.'});req.user.name=name;await req.user.save();res.json({success:true,user:req.user.toSafeObject()});}catch(e){next(e);}});
router.post('/change-password',requireActiveAccount,async(req,res,next)=>{try{const current=String(req.body.currentPassword||''),nextPassword=String(req.body.newPassword||'');if(nextPassword.length<8)return res.status(400).json({success:false,message:'New password must be at least 8 characters.'});const u=await User.findById(req.user._id).select('+passwordHash');if(!u||!(await bcrypt.compare(current,u.passwordHash)))return res.status(400).json({success:false,message:'Current password is incorrect.'});u.passwordHash=await bcrypt.hash(nextPassword,Number(process.env.BCRYPT_ROUNDS||12));u.sessionVersion=(u.sessionVersion||0)+1;u.failedLoginAttempts=0;u.lockedUntil=null;await u.save();res.json({success:true,message:'Password changed successfully.'});}catch(e){next(e);}});
router.get('/account',requireActiveAccount,(req,res)=>res.json({success:true,account:{id:req.user._id,name:req.user.name,email:req.user.email,status:req.user.status,role:req.user.role,referralCode:req.user.referralCode,availableBalance:req.user.availableBalance.toString(),reservedBalance:req.user.reservedBalance.toString(),totalDeposited:req.user.totalDeposited.toString(),totalWithdrawn:req.user.totalWithdrawn.toString(),directReferralsCount:req.user.directReferralsCount,totalReferralsCount:req.user.totalReferralsCount}}));
router.get('/kyc',async(req,res,next)=>{try{const k=await KycProfile.findOne({user:req.user._id}).lean();res.json({success:true,kyc:k?{status:k.status,fullName:k.fullName,country:k.country,documentType:k.documentType,documentNumberLast4:k.documentNumberLast4,riskLevel:k.riskLevel,rejectionReason:k.rejectionReason}:null});}catch(e){next(e)}});
router.patch('/kyc',async(req,res,next)=>{try{const documentType=String(req.body.documentType||'');if(!['passport','national_id','drivers_license'].includes(documentType))return res.status(400).json({success:false,message:'Select a valid document type.'});const last4=String(req.body.documentNumberLast4||'').trim();if(!/^[A-Za-z0-9]{4}$/.test(last4))return res.status(400).json({success:false,message:'Document last four characters are required.'});const fullName=String(req.body.fullName||'').trim();const country=String(req.body.country||'').trim();if(fullName.length<2||country.length<2)return res.status(400).json({success:false,message:'Legal name and country are required.'});const k=await KycProfile.findOneAndUpdate({user:req.user._id},{user:req.user._id,status:'pending',fullName:fullName.slice(0,120),country:country.slice(0,80),documentType,documentNumberLast4:last4,riskLevel:'low',sanctionsScreened:false,amlReviewed:false,reviewedBy:null,reviewedAt:null,rejectionReason:''},{upsert:true,new:true,runValidators:true});res.json({success:true,kyc:{status:k.status}});}catch(e){next(e)}});

router.get('/notifications',async(req,res,next)=>{try{const N=require('../models/AdminNotification');const items=await N.find({$or:[{user:req.user._id},{user:null,group:{$in:['all','users']}}]}).sort({createdAt:-1}).limit(100).lean();res.json({success:true,items});}catch(e){next(e)}});
router.get('/support/tickets',async(req,res,next)=>{try{const T=require('../models/SupportTicket');const items=await T.find({user:req.user._id}).sort({updatedAt:-1}).limit(50).lean();res.json({success:true,items});}catch(e){next(e)}});
router.post('/support/tickets',requireActiveAccount,async(req,res,next)=>{try{const T=require('../models/SupportTicket');const subject=String(req.body.subject||'').trim().slice(0,200);const message=String(req.body.message||'').trim().slice(0,5000);if(subject.length<2||message.length<2)return res.status(400).json({success:false,message:'الموضوع والرسالة مطلوبان.'});const t=await T.create({user:req.user._id,subject,messages:[{sender:req.user._id,body:message}],status:'open'});res.status(201).json({success:true,ticket:t});}catch(e){next(e)}});
router.post('/support/tickets/:id/reply',requireActiveAccount,async(req,res,next)=>{try{const T=require('../models/SupportTicket');const t=await T.findOne({_id:req.params.id,user:req.user._id});if(!t)return res.status(404).json({success:false,message:'التذكرة غير موجودة.'});const message=String(req.body.message||'').trim().slice(0,5000);if(message.length<2)return res.status(400).json({success:false,message:'الرسالة مطلوبة.'});t.messages.push({sender:req.user._id,body:message});if(t.status==='resolved')t.status='open';await t.save();res.json({success:true,ticket:t});}catch(e){next(e)}});
module.exports=router;
