const jwt=require('jsonwebtoken'); const User=require('../models/User');
function readCookie(req,name){const raw=req.headers.cookie||'';for(const part of raw.split(';')){const [k,...v]=part.trim().split('=');if(k===name)return decodeURIComponent(v.join('='));}return null;}
function getBearerToken(req){const h=req.headers.authorization||'';if(h.startsWith('Bearer '))return h.slice(7).trim();return readCookie(req,'ci_session');}
async function requireAuth(req,res,next){try{const token=getBearerToken(req);if(!token)return res.status(401).json({success:false,message:'Authentication required.'});const p=jwt.verify(token,process.env.JWT_SECRET,{algorithms:['HS256'],issuer:'crypinvest',audience:'crypinvest-users'});if(!p.sub)return res.status(401).json({success:false,message:'Invalid session.'});const user=await User.findById(p.sub);if(!user)return res.status(401).json({success:false,message:'Account not found.'});if(Number(p.sv||0)!==Number(user.sessionVersion||0))return res.status(401).json({success:false,message:'Session expired. Please sign in again.'});if(['suspended','blocked'].includes(user.status))return res.status(403).json({success:false,message:'Account is not available.'});if(user.isLocked)return res.status(423).json({success:false,message:'Account is temporarily locked.'});req.user=user;req.auth=p;req.authViaCookie=!req.headers.authorization;next();}catch(e){return res.status(401).json({success:false,message:'Invalid or expired session.'});}}
const ADMIN_ROLES=['super_admin','admin','support','finance','auditor','content_manager'];
const ROLE_PERMISSIONS={super_admin:['*'],admin:['users:read','users:write','transactions:read','transactions:write','support:read','support:write'],support:['users:read','support:read','support:write'],finance:['users:read','transactions:read','deposits:read','deposits:write','withdrawals:read','withdrawals:write','reports:read','networks:read','tokens:read'],auditor:['users:read','transactions:read','deposits:read','withdrawals:read','investments:read','plans:read','networks:read','tokens:read','copy:read','reports:read','audit:read'],content_manager:['notifications:read','notifications:write','content:read','content:write']};
function requireAdmin(req,res,next){if(!req.user||!ADMIN_ROLES.includes(req.user.role))return res.status(403).json({success:false,message:'Admin access required.'});next();}
function hasPermission(role,permission){const p=ROLE_PERMISSIONS[role]||[];return p.includes('*')||p.includes(permission);}
function requirePermission(permission,{write=false,sensitive=false}={}){return (req,res,next)=>{if(!req.user||!ADMIN_ROLES.includes(req.user.role)||!hasPermission(req.user.role,permission))return res.status(403).json({success:false,message:'ليس لديك صلاحية لهذا الإجراء.',code:'ADMIN_PERMISSION_DENIED'});if(write&&!['GET','HEAD','OPTIONS'].includes(req.method)&&req.authViaCookie&&req.get('x-csrf-guard')!=='1')return res.status(403).json({success:false,message:'CSRF protection required.'});if(sensitive&&req.get('x-admin-confirm')!=='1')return res.status(428).json({success:false,message:'تأكيد إضافي مطلوب لهذه العملية.',code:'ADMIN_CONFIRMATION_REQUIRED'});next();};}
function adminRoles(){return ADMIN_ROLES.slice();}
function permissionsForRole(role){return ROLE_PERMISSIONS[role]||[];}
function requireActiveAccount(req,res,next){if(!req.user||req.user.status!=='active')return res.status(403).json({success:false,message:'Active account required.'});next();}
function requireCsrfForCookie(req,res,next){if(['GET','HEAD','OPTIONS'].includes(req.method))return next();const hasCookie=Boolean(readCookie(req,'ci_session'));const hasBearer=Boolean(req.headers.authorization&&req.headers.authorization.startsWith('Bearer '));if(hasCookie&&!hasBearer&&req.get('x-csrf-guard')!=='1')return res.status(403).json({success:false,message:'CSRF protection required.'});next();}
async function optionalAuth(req,res,next){try{const token=getBearerToken(req);if(token){const p=jwt.verify(token,process.env.JWT_SECRET,{algorithms:['HS256'],issuer:'crypinvest',audience:'crypinvest-users'});req.user=await User.findById(p.sub);if(req.user&&Number(p.sv||0)!==Number(req.user.sessionVersion||0))req.user=null;req.auth=p;req.authViaCookie=!req.headers.authorization;}}catch{} next();}
module.exports={getBearerToken,requireAuth,requireAdmin,requireActiveAccount,optionalAuth,requireCsrfForCookie,readCookie,requirePermission,hasPermission,permissionsForRole,adminRoles,ADMIN_ROLES,ROLE_PERMISSIONS};
